version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5430:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=super
      - POSTGRES_DB=billquest